### ISSUE TITLE
Error OpaqueToken

### ISSUE THREAD

**Issue by HansS** [RaphaelJenni/FirebaseUIAngularIntegration#2]
ERROR in Error encountered resolving symbol values statically. Calling function 'OpaqueToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol FirebaseUserConfig in C:/Users/Folio/web/firebase-authentication/FirebaseUI-Angular/FirebaseUIAngularIntegrationSample/node_modules/angularfire2/tokens.d.ts, resolving symbol AngularFireModule.initializeApp in C:/Users/Folio/web/firebase-authentication/FirebaseUI-Angular/FirebaseUIAngularIntegrationSample/node_modules/angularfire2/angularfire2.d.ts, resolving symbol AppModule in C:/Users/Folio/web/firebase-authentication/FirebaseUI-Angular/FirebaseUIAngularIntegrationSample/src/app/app.module.ts, resolving symbol AppModule in C:/Users/Folio/web/firebase-authentication/FirebaseUI-Angular/FirebaseUIAngularIntegrationSample/src/app/app.module.ts

**Comment by RaphaelJenni** [comment]
This repository isn't maintained anymore. Please use or checkout https://github.com/RaphaelJenni/FirebaseUI-Angular
